---
# tasks file for rundeck
- name: Garantir o Java - Instalando
  yum: name=java state=present

- name: Download do Repositorio Rundeck
  yum: name=http://repo.rundeck.org/latest.rpm state=present

- name: Instalando o Rundeck
  yum: name=rundeck state=present
