---
- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - wget

- name: Add Puppet Labs apt key.
  apt_key:
    url: https://apt.puppetlabs.com/DEB-GPG-KEY-puppetlabs
    state: present

- name: Download do repositorio
    get_url: url=https://apt.puppetlabs.com/puppet5-release-xenial.deb
    dest: /tmp/puppet5-release-xenial.deb

- name: Instalando o pacote .DEB
  command: dpkg -i /tmp/puppet5-release-xenial.deb

- name: Instalando o puppet e o puppet lint
  apt: name={{item}} update_cache=yes state=present
  with_items:
  - puppet
  - puppet-lint
