---
# tasks files for puppet
- name: Download do Repositorio
  get_url:
    url: https://apt.puppetlabs.com/puppet5-release-{{ ansible_distribution_release}}.deb
    dest: /tmp/puppet5-release-{{ ansible_distribution_release}}.deb

- name: Instalando o pacote .DEB
  command: dpkg -i /tmp/puppet5-release-{{ ansible_distribution_release}}.deb


- name: Instalar o puppet e o puppet lint
  apt: name={{item}} update_cache=yes state=present

  with_items:
      - puppet
      - puppet-lint
